[package]
name = "logos-cli"
version = "0.12.0"
license = "MIT OR Apache-2.0"
description = "Create ridiculously fast Lexers"
repository = "https://github.com/maciejhirsz/logos"
documentation = "https://docs.rs/logos-derive"
keywords = ["lexer", "lexical", "tokenizer", "parser", "no_std"]
categories = ["parsing", "text-processing"]
readme = "../README.md"
edition = "2018"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
fs-err = "2.7.0"
logos-codegen = { path = "../logos-codegen", version = "0.12.0" }
proc-macro2 = "1.0.39"
